package com.bstc.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.pdf.PdfRenderer;import android.content.*;import android.content.res.AssetFileDescriptor;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import android.database.Cursor;

public class MainActivity extends Activity {
    LinearLayout root,content; BSTCDbHelper db; boolean dark=false; int blue=Color.rgb(27,73,101); ArrayList<Question> current=new ArrayList<>();
    public void onCreate(Bundle b){super.onCreate(b);db=new BSTCDbHelper(this);dark=getPreferences(0).getBoolean("dark",false);build();home();}
    TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(dark?Color.WHITE:Color.rgb(23,32,42));t.setPadding(20,14,20,14);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);return b;}
    void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(dark?Color.rgb(25,29,32):Color.rgb(246,248,250));
      TextView head=tv("BSTC\nआपकी BSTC तैयारी, एक ही जगह।",22);head.setTextColor(Color.WHITE);head.setBackgroundColor(blue);head.setPadding(22,24,22,20);root.addView(head,new LinearLayout.LayoutParams(-1,-2));
      content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
      LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);String[] n={"🏠 HOME","❓ MCQs","📝 OLD PAPERS","🎯 MOCK","📊 RESULTS","⚙ SETTINGS"};for(String x:n){Button b=btn(x);b.setTextSize(11);nav.addView(b,new LinearLayout.LayoutParams(0,58,1));final String z=x;b.setOnClickListener(v->{if(z.contains("HOME"))home();else if(z.contains("MCQ"))mcqs();else if(z.contains("OLD"))oldPapers();else if(z.contains("MOCK"))mockMenu();else if(z.contains("RESULT"))results();else settings();});}root.addView(nav);setContentView(root);}
    void clear(){content.removeAllViews();}
    void title(String s){TextView t=tv(s,22);t.setTypeface(null,1);content.addView(t);}
    void card(String s){TextView t=tv(s,16);t.setBackgroundColor(dark?Color.rgb(45,50,54):Color.WHITE);content.addView(t,new LinearLayout.LayoutParams(-1,-2));}
    void home(){clear();title("🏠 Home");card("Quick Start\nPractice source-based MCQs from the supplied BSTC papers.");Button b=btn("Start Practice");content.addView(b);b.setOnClickListener(v->practice("All Subjects",10));card("My Progress\nYour test history is stored locally on this device.");card("Today's Practice\nNo internet • No login • No ads");card("Source set: 2020–2025 papers + official 2026-27 syllabus.");}
    void mcqs(){clear();title("❓ MCQs");String[] ss={"Mental Ability","Rajasthan GK","Teaching Aptitude","English","Hindi","Sanskrit","All Subjects"};for(String s:ss){Button b=btn(s);content.addView(b);b.setOnClickListener(v->practice(s,10));}card("⚠ Source accuracy: items without an attached official answer key are marked as derived/unverified inside the question view.");}
    void practice(String subject,int limit){current=db.questions(subject);if(current.size()>limit)current=new ArrayList<>(current.subList(0,limit));if(current.isEmpty()){toast("No questions available");return;}final int[] idx={0};final int[] selected=new int[current.size()];Arrays.fill(selected,-1);clear();title("Practice • "+subject);renderQuestion(idx,selected);}
    void renderQuestion(int[] idx,int[] selected){clear();Question q=current.get(idx[0]);TextView meta=tv("Question "+(idx[0]+1)+" / "+current.size()+"\n"+q.subject+" • "+q.topic,15);content.addView(meta);TextView qt=tv(q.q,19);qt.setTypeface(null,1);content.addView(qt);for(int i=0;i<4;i++){RadioButton r=new RadioButton(this);r.setText((char)('A'+i)+". "+q.options[i]);r.setTextSize(16);r.setChecked(selected[idx[0]]==i);final int k=i;r.setOnClickListener(v->selected[idx[0]]=k);content.addView(r);}card("Source: "+q.source+(q.verified?"\nAnswer status: verified":"\nAnswer status: derived/unverified"));LinearLayout row=new LinearLayout(this);if(idx[0]>0){Button p=btn("Previous");row.addView(p,new LinearLayout.LayoutParams(0,-2,1));p.setOnClickListener(v->{idx[0]--;renderQuestion(idx,selected);});}if(idx[0]<current.size()-1){Button n=btn("Next");row.addView(n,new LinearLayout.LayoutParams(0,-2,1));n.setOnClickListener(v->{idx[0]++;renderQuestion(idx,selected);});}else{Button s=btn("Submit");row.addView(s,new LinearLayout.LayoutParams(0,-2,1));s.setOnClickListener(v->finishTest(selected));}content.addView(row);}
    void finishTest(int[] selected){int c=0,w=0,u=0;for(int i=0;i<current.size();i++){if(selected[i]<0)u++;else if(selected[i]==current.get(i).answer)c++;else w++;}int score=c*3;db.addResult("Practice/Mock",score,current.size()*3,c,w,u);clear();title("Result");card("Score: "+score+" / "+(current.size()*3)+"\nCorrect: "+c+"\nWrong: "+w+"\nUnattempted: "+u);Button b=btn("Back to Home");content.addView(b);b.setOnClickListener(v->home());}
    void oldPapers(){clear();title("📝 Old Papers");String[] files={"2020.pdf","2021.pdf","2022.pdf","2023.pdf","2024.pdf","2025 1st shift.pdf","2025 2nd shift.pdf"};for(String f:files){Button b=btn(f.replace(".pdf",""));content.addView(b);b.setOnClickListener(v->openPdf(f));}card("Actual supplied PDFs are opened locally. No conversion into test mode.");}
    void openPdf(String name){try{File out=new File(getCacheDir(),name);if(!out.exists()){InputStream in=getAssets().open("papers/"+name);FileOutputStream o=new FileOutputStream(out);byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)o.write(buf,0,n);o.close();in.close();}ParcelFileDescriptor pfd=ParcelFileDescriptor.open(out,ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer r=new PdfRenderer(pfd);final int[] page={0};clear();title(name);ImageView iv=new ImageView(this);iv.setAdjustViewBounds(true);content.addView(iv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout row=new LinearLayout(this);Button prev=btn("◀");Button next=btn("▶");TextView pg=tv("",14);row.addView(prev,new LinearLayout.LayoutParams(0,-2,1));row.addView(pg,new LinearLayout.LayoutParams(0,-2,2));row.addView(next,new LinearLayout.LayoutParams(0,-2,1));content.addView(row);Runnable render=()->{PdfRenderer.Page pp=r.openPage(page[0]);Bitmap bm=Bitmap.createBitmap(pp.getWidth(),pp.getHeight(),Bitmap.Config.ARGB_8888);bm.eraseColor(Color.WHITE);pp.render(bm,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);pp.close();iv.setImageBitmap(bm);pg.setText("Page "+(page[0]+1)+" / "+r.getPageCount());};prev.setOnClickListener(v->{if(page[0]>0){page[0]--;render.run();}});next.setOnClickListener(v->{if(page[0]<r.getPageCount()-1){page[0]++;render.run();}});render.run();}catch(Exception e){toast("PDF open error: "+e.getMessage());}}
    void mockMenu(){clear();title("🎯 Mock Tests");Button full=btn("Full Mock Test (official pattern: 200 Q / 600 marks)");content.addView(full);full.setOnClickListener(v->{toast("The current offline build only uses validated/seeded questions; it will not fabricate missing questions.");practice("All Subjects",10);});Button sub=btn("Subject-wise Mock Test");content.addView(sub);sub.setOnClickListener(v->mcqs());Button custom=btn("Custom Mock Test");content.addView(custom);custom.setOnClickListener(v->practice("All Subjects",10));card("Official pattern from supplied syllabus: 200 questions, 600 marks, no negative marking.");}
    void results(){clear();title("📊 Results");Cursor c=db.results();if(!c.moveToFirst())card("No tests completed yet.");else{do{String s=c.getString(c.getColumnIndexOrThrow("type"))+"\nScore: "+c.getInt(c.getColumnIndexOrThrow("score"))+" / "+c.getInt(c.getColumnIndexOrThrow("total"))+"\nCorrect: "+c.getInt(c.getColumnIndexOrThrow("correct"))+" • Wrong: "+c.getInt(c.getColumnIndexOrThrow("wrong"))+" • Unattempted: "+c.getInt(c.getColumnIndexOrThrow("unattempted"));card(s);}while(c.moveToNext());}c.close();Button clear=btn("Clear Test History");content.addView(clear);clear.setOnClickListener(v->{db.clearResults();results();});}
    void settings(){clear();title("⚙ Settings");Button d=btn("Dark / Light Mode");content.addView(d);d.setOnClickListener(v->{dark=!dark;getPreferences(0).edit().putBoolean("dark",dark).apply();build();settings();});Button s=btn("Sound: Off (lightweight build)");content.addView(s);Button lang=btn("Language: Hindi / English UI");content.addView(lang);Button vib=btn("Vibration: Off");content.addView(vib);Button reset=btn("Reset App Data");content.addView(reset);reset.setOnClickListener(v->{getPreferences(0).edit().clear().apply();db.clearAll();toast("Local progress cleared");home();});card("About App\nBSTC • Offline preparation app\nSource: supplied BSTC papers and official 2026-27 syllabus.");card("Privacy / Disclaimer\nNo login, no ads, no server. Verify redistribution rights before commercial distribution of third-party papers.");}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override public void onBackPressed(){home();}
}
